@startuml
    actor user as "User"
    rectangle db as "Database"
    rectangle "Populated Capital Function"{
        usecase PCaWORLD as "Populated Capital In The World"
        usecase PCaCONTINENT as "Populated Capital In The Continent"
        usecase PCaREGION as "Populated Capital In The Region"
        user - PCaWORLD
        user - PCaCONTINENT
        user - PCaREGION
        db --- PCaWORLD
        db --- PCaCONTINENT
        db --- PCaREGION
    }
@enduml