@startuml
           actor user as "User"
               note top of user: User can use several features in the system
               rectangle db as "Database"
               note right of db: This Database contains all of the population around the globe
           rectangle "Populated Countries Function"{
               usecase PCWORLD as "View Populated Countries In The World"
               usecase PCCONTINENT as "View Populated Countries In The Continent"
               usecase PCREGION as "View Populated Countries In The Region"
               user - PCWORLD
               user - PCCONTINENT
               user - PCREGION
               db --- PCWORLD
               db --- PCCONTINENT
               db --- PCREGION
           }
@enduml