@startuml
actor user as "User"
note right of user: User can use several features in the system
rectangle db as "Database"
note top of db: This Database contains all of the population around the globe
rectangle "Top N Populated Countries Function"{
    usecase input as "Limitation Input (N)"
    usecase PC1 as "View Populated Countries In The World"
    usecase PC2 as "View Populated Countries In a Continent"
    usecase PC3 as "View Populated Countries In a Region"
    db -- PC1
    db -- PC2
    db -- PC3
}
user -- input
input -- PC1
input -- PC3
input -- PC2

@enduml