@startuml
actor user as "User"
rectangle db as "Database"
rectangle "Top N Populated Capital Function"{
    usecase input as "Limitation Input (N)"
    usecase continent as "Continent Input"
    usecase region as "Region Input"
    usecase PC1 as "Populated Capital In The World"
    usecase PC2 as "Populated Capital In a Continent"
    usecase PC3 as "Populated Capital In a Region"
    db -- PC1
    db -- PC2
    db -- PC3
}
user -- input
input -- PC1
input -- continent
input -- region
continent -- PC2
region -- PC3

@enduml